primary_region = 'yyz'

[build]
  [build.args]
    GO_VERSION = '1.25.0'
    TARGET_BINARY = 'smoke_test'

[env]
  PROTO_UDP_ADDR = 'fly-global-services:4269'
  PROTO_LOG_LEVEL = 'debug'

[[services]]
  internal_port = 4269
  protocol = 'udp'
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[services.ports]]
    port = 4269

[[services]]
  internal_port = 4269
  protocol = 'tcp'
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[services.ports]]
    port = 4269

# [services.concurrency]
#   type = 'connections'
#   hard_limit = 5
#   soft_limit = 5

[[vm]]
  size = 'shared-cpu-1x'
